### ISSUE TITLE
Add button to let you submit levels to the site

### ISSUE THREAD

**Issue by siky112** [auburnsummer/rdlevels#1]
Hi, I'm working on a level and want to eventually submit it to the site but I don't know how. If there was a button to let you do this easier, that might be useful.

**Comment by auburnsummer** [comment]
Hi,

This website is serviced by the [Rhythm Doctor Discord server](https://discordapp.com/invite/rhythmdr). To upload a level to this site, you should post an .rdzip file in the #level-showcase channel of the Discord server. 

Out of curiosity, how did you find this site? I've only linked it from within the Discord server, so I am surprised to find someone find it from elsewhere.

**Comment by siky112** [comment]
noteldonte's youtube channel

**Comment by auburnsummer** [comment]
https://github.com/auburnsummer/rdlevels/commit/79a13a6931dfbaa2e9647115a72c3871f63a4129

I added a top bar which instructs the user to visit the Discord server if they want to add a level.
